### ISSUE TITLE
main.c example for toee

### ISSUE THREAD

**Issue by emxd** [alexbatalov/tig#1]
Hello,

just wondering, could you provide a main.c example that can run ToEE?

**Comment by alexbatalov** [comment]
Well, it's not that easy. Current implementation follows TIG found in Arcanum. TIG was improved for ToEE in order to support it's mixed 2D/3D environment. There are major changes in renderer (video module) accompanied by new supporting modules (texture, shader, gfx). In addition window/button system (Fallout's ancestry) was replaced with a more feature-rich UI framework called WFT. So at this time it's impossible to make use of ToEE resources or implement ToEE's main menu.

**Comment by alexbatalov** [comment]
Reversing Arcanum, yes. TIG is an OS abstraction library, albeit it only supports Windows. With this project I'd like to split porting task (ideally led by someone else) and reverse engineering task. Once the game is ready (or at least something compilable exists) it would be available on multiple platforms on day one.
